"""Constants for the PubliBike / Velospot integration."""

from __future__ import annotations

DOMAIN = "publibike"

API_ALL_STATIONS = "https://rest.publibike.ch/v1/public/all/stations"
API_BASE_OLD = "https://api.publibike.ch/v1"
API_PARTNER_STATIONS = f"{API_BASE_OLD}/public/partner/stations"
API_STATIONS = f"{API_BASE_OLD}/public/stations"
API_STATION_DETAIL = f"{API_BASE_OLD}/public/stations/{{station_id}}"

GEOCODE_URL = "https://api3.geo.admin.ch/rest/services/api/SearchServer"

CONF_ADDRESS = "address"
CONF_CITY = "city"
CONF_LATITUDE = "latitude"
CONF_LOCATION_NAME = "location_name"
CONF_LONGITUDE = "longitude"
CONF_MIN_EBIKE_BATTERY = "min_ebike_battery"
CONF_REFERENCE_TYPE = "reference_type"
CONF_STATION_ID = "station_id"
CONF_STATION_NAME = "station_name"
CONF_UPDATE_INTERVAL = "update_interval"

REFERENCE_TYPE_STATION = "station"
REFERENCE_TYPE_ADDRESS = "address"

DEFAULT_UPDATE_INTERVAL = 300
MIN_UPDATE_INTERVAL = 60
DEFAULT_TIMEOUT = 20
DEFAULT_MIN_EBIKE_BATTERY = 40  # km from v16; legacy constant name kept for compatibility
DEFAULT_CITY = "Zürich"

PLATFORMS = ["sensor", "button"]

ATTR_ADDRESS = "address"
ATTR_API_MODE = "api_mode"
ATTR_BATTERY_FILTER_AVAILABLE = "battery_filter_available"
ATTR_BIKE_LIST = "bike_list"
ATTR_EBIKE_DETAIL_LIST = "ebike_detail_list"
ATTR_BIKE_DETAIL_LIST = "bike_detail_list"
ATTR_API_LIMITATION = "api_limitation"
ATTR_VEHICLE_ID_AVAILABLE = "vehicle_id_available"
ATTR_BATTERY_PERCENT_AVAILABLE = "battery_percent_available"
ATTR_CAPACITY = "capacity"
ATTR_CITY = "city"
ATTR_CONFIGURED_CITY = "configured_city"
ATTR_DETAILS_ROUTE = "details_route"
ATTR_DISTANCE_AIR_M = "distance_air_m"
ATTR_EBIKE_BATTERY_LEVELS = "ebike_battery_levels"
ATTR_EBIKES = "ebikes"
ATTR_EBIKES_OVER_THRESHOLD = "ebikes_over_threshold"
ATTR_FREE_SPACES = "free_spaces"
ATTR_GEOCODE_SOURCE = "geocode_source"
ATTR_LAST_UPDATE = "last_update"
ATTR_LATITUDE = "latitude"
ATTR_LOCATION_NAME = "location_name"
ATTR_LONGITUDE = "longitude"
ATTR_MAP_ICON = "map_icon"
ATTR_MIN_EBIKE_BATTERY = "min_ebike_battery"  # legacy attribute name
ATTR_MIN_EBIKE_RANGE_KM = "min_ebike_range_km"
ATTR_EBIKE_RANGE_KM = "ebike_range_km"
ATTR_EBIKE_RANGE_AVAILABLE = "ebike_range_available"
ATTR_EBIKES_OVER_RANGE = "ebikes_over_range"
ATTR_RANGE_SOURCE = "range_source"
ATTR_NEAREST_BIKE = "nearest_bike"
ATTR_NEAREST_EBIKE = "nearest_ebike"
ATTR_NETWORK = "network"
ATTR_NORMAL_BIKES = "normal_bikes"
ATTR_RAW_STATION_COUNT = "raw_station_count"
ATTR_REFERENCE_TYPE = "reference_type"
ATTR_SELECTED_STATION = "selected_station"
ATTR_SOURCE = "source"
ATTR_SOURCE_ENDPOINT = "source_endpoint"
ATTR_STATUS = "status"
ATTR_STATION_ID = "station_id"
ATTR_STATION_NAME = "station_name"
ATTR_STATION_NUMBER = "station_number"
ATTR_TOTAL_BIKES = "total_bikes"
ATTR_UPDATE_INTERVAL = "update_interval"
ATTR_VEHICLE_DETAILS_AVAILABLE = "vehicle_details_available"
ATTR_VEHICLE_LIST_NOTE = "vehicle_list_note"
ATTR_WARNING = "warning"
ATTR_WALKING_DISTANCE_ESTIMATE_M = "walking_distance_estimate_m"
ATTR_WALKING_TIME_ESTIMATE_MIN = "walking_time_estimate_min"
ATTR_AVAILABLE_REASON = "available_reason"
ATTR_MATCHING_VEHICLE_TYPE = "matching_vehicle_type"
ATTR_VEHICLE_TABLE = "vehicle_table"
ATTR_VEHICLE_TABLE_MARKDOWN = "vehicle_table_markdown"
ATTR_EBIKE_TABLE = "ebike_table"
ATTR_BIKE_TABLE = "bike_table"
ATTR_VEHICLE_DETAIL_SOURCE = "vehicle_detail_source"
ATTR_KM_POTENTIAL = "km_potential"
ATTR_BATTERY_PERCENT_ESTIMATE = "battery_percent_estimate"
ATTR_BATTERY_PERCENT_ESTIMATED = "battery_percent_estimated"
ATTR_EBIKE_TABLE_MARKDOWN = "ebike_table_markdown"
ATTR_BIKE_TABLE_MARKDOWN = "bike_table_markdown"
ATTR_NEAREST_STATION_TYPE = "nearest_station_type"
